### ISSUE TITLE
Add comments

### ISSUE THREAD

**Issue by ghost** [Arielus99/prj-rev-bwfs-dasmoto#3]
Add comments

https://github.com/Arielus99/prj-rev-bwfs-dasmoto/blob/88d0454b04833fcc22d01d6a85b4adc73703b744/DevProject/index.html#L13

**Comment by JakeLBeans** [comment]
What's the issue? 

If you would like to create comments in HTML use the following but remove the “ marks. 

“<“!-- Comment goes here --“>”

**Comment by Arielus99** [comment]
I'm not sure to understand what do you mean. The line 13 is empty. 
Am I missing something?

**Comment by JakeLBeans** [comment]
Sorry just updated my reply. If you’re trying to add comments in HTML then use the following but REMOVE the quotation “ marks:

 “<“!-- Comment goes here --“>”
